# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  # pull_request:
  # branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run deploy bash script
        run: |
          mkdir -p $HOME/.ssh
          eval `ssh-agent -s`
          echo "${{secrets.DEPLOY_KEY}}" > $HOME/.ssh/id_rsa
          ssh-add $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.HOSTNAME}} >> $HOME/.ssh/known_hosts
          ./deploy/deploy.sh $HOME/.ssh/id_rsa && echo "done!"
